[workspace]
resolver = "2"
members = [
    "crates/servitor-api",
    "crates/servitor-ledger",
    "crates/servitor-worker",
    "crates/servitor-proto",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3